# Generated by Django 5.0.6 on 2024-05-10 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AugmentedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30, verbose_name='Почта')),
                ('amount_completed_tasks', models.PositiveIntegerField(default=0, verbose_name='Количество выполненных обращений')),
                ('amount_running_tasks', models.PositiveIntegerField(default=0, verbose_name='Количество текущих обращений')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Встроенный пользователь')),
            ],
            options={
                'verbose_name': 'Расширенный пользователь',
                'verbose_name_plural': 'Расширенные пользователи',
                'db_table': 'augmented_user',
            },
        ),
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='ФИО ученика')),
                ('skype', models.CharField(max_length=45, verbose_name='Скайп ученика')),
                ('massage', models.CharField(max_length=1000, verbose_name='Обращение')),
                ('headset', models.CharField(choices=[('USB', 'USB'), ('3.5', '3.5'), ('USB/3.5', '3.5 наушники и USB микрофон'), ('3.5/USB', 'USB наушники и 3.5 микрофон')], max_length=10, null=True, verbose_name='Гарнитура\\микрофон')),
                ('sound_is_ok', models.BooleanField(null=True, verbose_name='Звук ученика')),
                ('date_of_group_start', models.DateField(null=True, verbose_name='Дата старта группы')),
                ('lead_time', models.PositiveIntegerField(blank=True, null=True, verbose_name='Время выполнения')),
                ('is_complete', models.BooleanField(default=False, verbose_name='Завершено')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.augmenteduser', verbose_name='Кто выполняет')),
            ],
            options={
                'verbose_name': 'Обращение',
                'verbose_name_plural': 'Обращения',
                'db_table': 'appeal',
                'default_related_name': 'appeals',
            },
        ),
    ]
