# Generated by Django 5.0.6 on 2024-05-15 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='date_of_group_start',
            field=models.DateField(blank=True, null=True, verbose_name='Дата старта группы'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='headset',
            field=models.CharField(blank=True, choices=[('USB', 'USB'), ('3.5', '3.5'), ('USB/3.5', '3.5 наушники и USB микрофон'), ('3.5/USB', 'USB наушники и 3.5 микрофон')], max_length=10, null=True, verbose_name='Гарнитура\\микрофон'),
        ),
    ]
