# Generated by Django 5.0.6 on 2024-11-08 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeal',
            name='camera',
            field=models.BooleanField(blank=True, null=True, verbose_name='Камера'),
        ),
        migrations.AddField(
            model_name='appeal',
            name='speed_test',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Тест скорости'),
        ),
        migrations.AddField(
            model_name='appeal',
            name='speed_test_note',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Комментарий к тесту скорости'),
        ),
    ]
