# Generated by Django 5.0.6 on 2024-05-29 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_appeal_date_of_group_start_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appeal',
            old_name='massage',
            new_name='message',
        ),
    ]
