# Generated by Django 5.0.6 on 2024-11-11 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_appeal_camera_appeal_speed_test_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='augmenteduser',
            name='name',
            field=models.CharField(default='test', max_length=50, verbose_name='Имя инженера'),
            preserve_default=False,
        ),
    ]
