# Generated by Django 5.0.6 on 2024-11-11 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_augmenteduser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeal',
            name='student_note',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Комментарий к ученику'),
        ),
    ]
