# Generated by Django 5.0.6 on 2024-11-21 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_appeal_student_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeal',
            name='appeal_type',
            field=models.CharField(blank=True, choices=[('Проверка', 'Проверка'), ('Инцидент', 'Инцидент')], max_length=10, null=True, verbose_name='Тип обращения'),
        ),
    ]
