# Generated by Django 5.0.6 on 2024-06-21 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_appeal_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appeal',
            old_name='deleted',
            new_name='is_deleted',
        ),
    ]
