# Generated by Django 5.0.6 on 2024-11-23 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_appeal_appeal_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeal',
            name='is_spam',
            field=models.BooleanField(default=False, verbose_name='Спам'),
        ),
    ]
