# Generated by Django 5.0.6 on 2024-12-05 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_appeal_is_spam'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeal',
            name='time_to_complete',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Время на проверку'),
        ),
        migrations.AddField(
            model_name='appeal',
            name='type_of_connection',
            field=models.CharField(blank=True, choices=[('wi-fi', 'wi-fi'), ('cable', 'кабель')], max_length=10, null=True, verbose_name='Тип подключения'),
        ),
    ]
