# Generated by Django 5.0.6 on 2024-12-11 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_appeal_time_to_complete_appeal_type_of_connection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appeal',
            old_name='appeal_type',
            new_name='type',
        ),
    ]
