# Generated by Django 5.0.6 on 2025-01-21 06:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_augmenteduser_engineer'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeal',
            name='date_of_create',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
    ]
