# Generated by Django 5.0.6 on 2025-01-31 07:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_appeal_date_of_create'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='engineer',
            options={'verbose_name': 'Инженер', 'verbose_name_plural': 'Инженеры'},
        ),
        migrations.AlterField(
            model_name='appeal',
            name='date_of_create',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
    ]
